import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { ArrowRight, BrainCircuit, CheckCircle2, FileCheck2, Network, Target, Users } from "lucide-react";

const pillars = [
  { icon: Target, title: "Competency intelligence", body: "Map role requirements to validated capability instead of treating course completion as competence." },
  { icon: BrainCircuit, title: "Explainable skill gaps", body: "Prioritise gaps using deterministic, reviewable rules for criticality, recency, and prerequisites." },
  { icon: FileCheck2, title: "Evidence-based verification", body: "Capture secure evidence and route it to trainers before competency records change." },
  { icon: Users, title: "Trainer matching", body: "Connect learners to relevant expertise with transparent weighted matching factors." },
  { icon: Network, title: "Organizational capability", body: "Aggregate verified competency signals into an operating view for leaders." },
];

export default function Landing() {
  return <div className="landing-shell"><header className="landing-nav"><div className="brand"><div className="brand-mark"><Target size={19} /></div><div><div className="brand-name">capacity<span>connect</span></div><div className="brand-sub">Competency intelligence platform</div></div></div><div className="landing-actions"><a href="#how-it-works">How it works</a><Button variant="outline" onClick={() => startLogin()}>Sign in <ArrowRight size={15} /></Button></div></header><main><section className="landing-hero"><div className="landing-hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> COMPETENCY INTELLIGENCE FOR ORGANIZATIONAL LEARNING</div><h1>Turn learning activity into <em>capability signal.</em></h1><p>Most LMS platforms can tell you whether someone completed a course. Capacity Connect goes further: it identifies competency gaps, connects people to relevant learning, captures evidence, gets capability verified, and measures organizational readiness.</p><div className="landing-cta"><Button className="primary-action" onClick={() => startLogin()}>Explore the platform <ArrowRight size={16} /></Button><span><CheckCircle2 size={15} /> Server-authoritative and evidence-led</span></div></div><div className="landing-signal"><div className="signal-kicker">THE CLOSED LOOP</div><div className="signal-title">From role definition<br />to verified capability</div>{["Role requirements", "Learning intervention", "Evidence + assessment", "Trainer verification", "Organization signal"].map((label, index) => <div className={`signal-step ${index === 2 ? "active" : ""}`} key={label}><span>{String(index + 1).padStart(2, "0")}</span><strong>{label}</strong><ArrowRight size={14} /></div>)}</div></section><section id="how-it-works" className="landing-pillars"><div className="eyebrow"><span className="eyebrow-line" /> ONE SYSTEM, ONE COMPETENCY LIFECYCLE</div><h2>The LMS is one part of the operating system.</h2><div className="pillar-grid">{pillars.map(({ icon: Icon, title, body }) => <article key={title}><div className="pillar-icon"><Icon size={18} /></div><h3>{title}</h3><p>{body}</p></article>)}</div></section></main><footer className="landing-footer"><span>CAPACITY CONNECT · SIH PS 26075</span><span>Built for traceable, organization-level capability improvement.</span></footer></div>;
}
